### ISSUE TITLE
Chrome App vs. Container Version numbers

### ISSUE THREAD

**Issue by tom472** [lexandro/dockermon#4]
I have been doing some testing with Dockery lately and I really like it.
I was wondering why the Chrome App version is 0.2.9
And the Docker Image is version is 0.3.0

Are you going to continue development of both the App and the Image?

Thanks
--Tom

**Comment by lexandro** [comment]
The Chrome app only gets updated when I finished the planned roadmap for the given version. The docker image is automatically built by the docker hub system.

If you want to get every new staff immediately use the image, otherwise I suggest to wait to the chrome updates, because I update only, when I feel mature enough.

I'm actively developing the code, but this is the summer and I'm taking a short break to enjoy the weather, etc :)

Btw any suggestions are welcome to improve it :)

Cheers,
Robert

**Comment by tom472** [comment]
OK so using the Docker image has not been working as well as the Chrome App.
Do you know if you have tried using the image to control a host running Boot2Docker?

Here is what I am trying on a test host:
Running boot2docker off a usb thumbdrive
Adjusting TLS=off in boot2docker for the API
Restart Docker - 
Launch dockery image via:
`docker run -d -p 80:80 lexandro/dockery`
At this point I can reach the dockery UI via the host IP on port 80 - 
However when I put http://<host ip>:2375 into the dockery UI it does not connect to the Docker API.

From a different PC using the Chrome App and using the same Docker host IP:2375 the app is able to connect no problem.

Is there any issue trying to run the image, connect to it, and control Docker on the same host?

**Comment by lexandro** [comment]
With the Docker image you can get all new developments with all new risks :)

The image versions are set manually in hub builds, because it can't track the github tags automatically. Personally I use both, but the chrome app has some limits (no back button for example, but I'm working on it) 

I used boot2docker for a short time, then I switched to a full ubuntu image and now I'm a linux user since 3 months (thanks to the docker :) ), please forgive me if I can't provide proper details about boot2docker usage.

I think you could read the dockery readme.md to change the docker daemon config file and enable remote access, because by default the daemon only listening on unix://var/run/docker.sock, so you need something like this:
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -api-enable-cors"

on my linux I found this in the /etc/default/docker file, but on boot2docker I'm not sure :)

And also you could check the IP address of boot2docker, because the localhost is pointing to your host machine not to the boot2docker.

Robert

**Comment by lexandro** [comment]
Dockery is released as hosted app. From now you don't need the image or the chrome app itself, just bookmark the following address: http://dockery.io/dockery 

Robert

**Comment by lexandro** [comment]
Ping. In case of no feedback I'm going to close this ticket.

**Comment by tom472** [comment]
Wow that's cool.
I'll have to play with that new app a bit.
But yes you can close this ticket.

Thanks

**Comment by lexandro** [comment]
Ok. :) When you found stg dont' hesitate to share with me. A lot of things are undone, but this is summertime :) :) :)
